// packages/source-solid/fixtures/solid-app/src/App.tsx
import Counter from './components/Counter'
import List from './components/List'

export function App() {
  const saved = localStorage.getItem('visits')
  const visits = saved === null ? 0 : Number(saved)
  localStorage.setItem('visits', String(visits + 1))

  return (
    <main>
      <h1>{visits} visits</h1>
      <Counter />
      <List />
    </main>
  )
}

// packages/source-angular/fixtures/angular-app/src/app/app.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-root',
  standalone: true,
  template: '<h1>{{ visits }} visits</h1>',
})
export class AppComponent {
  readonly visits = readVisits()
}

function readVisits(): number {
  const saved = localStorage.getItem('visits')
  localStorage.setItem('visits', String(Number(saved ?? '0') + 1))
  return Number(saved ?? '0')
}
