// packages/source-vue/fixtures/vue-app/src/App.vue
<script setup lang="ts">
import Counter from './components/Counter.vue'

const saved = localStorage.getItem('visits')
const visits = saved === null ? 0 : Number(saved)
localStorage.setItem('visits', String(visits + 1))
</script>

<template>
  <main>
    <h1>{{ visits }} visits</h1>
    <Counter />
  </main>
</template>

<style scoped>
main {
  padding: 1rem;
}
</style>

// packages/source-next/fixtures/next-app/app/page.tsx
import { Counter } from '../src/components/Counter'

export default function Home(): JSX.Element {
  const saved = localStorage.getItem('visits')
  localStorage.setItem('visits', String(Number(saved ?? '0') + 1))

  return (
    <main>
      <h1>{saved ?? '0'} visits</h1>
      <Counter />
    </main>
  )
}
