// packages/source-angular/fixtures/angular-app/src/app/components/name-input.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-name-input',
  standalone: true,
  template: '<input [value]="name" (input)="onInput($event)" />',
})
export class NameInputComponent {
  name = ''

  onInput(event: Event): void {
    this.name = (event.target as HTMLInputElement).value
  }

  get valid(): boolean {
    return this.name.trim().length > 0
  }
}

// packages/source-react/fixtures/react-app/src/components/NameInput.tsx
import { useState } from 'react'

export function NameInput(): JSX.Element {
  const [name, setName] = useState('')

  return (
    <div>
      <input value={name} onChange={(event) => setName(event.target.value)} />
      {name.trim().length === 0 ? <p>a name is required</p> : null}
    </div>
  )
}
